services:
  redis:
    image: redis:7
    restart: always
    networks:
      - backend

  db:
    image: postgres:17
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - LPfVM_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    platform: linux/amd64
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: config.settings
    networks:
      - backend

  celery_worker:
    build: .
    platform: linux/amd64
    command: uv run celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: config.settings
    networks:
      - backend

  celery_beat:
    build: .
    platform: linux/amd64
    command: uv run celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: config.settings
    networks:
      - backend

volumes:
  LPfVM_data:

networks:
  backend:
    driver: bridge
