# Generated by Django 6.0.3 on 2026-04-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='about',
            field=models.CharField(blank=True, choices=[('INCOME', '입금'), ('EXPENSE', '출금')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='type',
            field=models.CharField(blank=True, choices=[('weekly', '매주'), ('monthly', '매월')], default='', max_length=50),
        ),
    ]
