# Generated by Django 6.0.3 on 2026-04-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
    ]
