# Generated by Django 6.0.3 on 2026-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('transaction', '0004_transaction_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-transaction_date', '-created_at'], name='transaction_transac_63c5c1_idx'),
        ),
    ]
